[package]
name = "ccm-lang-js-ts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ccm-core.workspace = true
tree-sitter.workspace = true
tree-sitter-javascript = "0.25.0"
tree-sitter-typescript = "0.23.2"

[dev-dependencies]
ccm-index.workspace = true
