[package]
name = "ccm-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.104"
ccm-core.workspace = true
ccm-index.workspace = true
ccm-lang-python.workspace = true
ccm-lang-rust.workspace = true
clap = { version = "4.6.6", features = ["derive"] }
